--[[

This software is released under the MIT License. See LICENSE.txt for details.

Also, on a non-legal note: I do not recommend reading my code, especially not for educative
purposes. It was written over like three years, and I often forgot how I implemented several
things over time. Also, I was mostly drunk and listening to the Katamari Damacy soundtrack. 
So yeah.

]]

local tits = {}

local function a(s)
	table.insert(tits,s)
end
tits[0] = "trololOlo"


a "well, like they say in brooklyn!"
a "that's what she said!"
a "that's what she said!"
a "that's what she said!"
a "your mom!"
a "it's a secret to everybody!"
a "...but then i took an arrow in the knee"
a "desu"
a "all my base are belong to you"
a "gaming brilliance"
a "jitsu wa... hamu desu."
a "that's what she said!"
a "makes you smarter"
a "makes you awesome"
a "makes you invincible"
a "makes you invisible"
a "makes you fart"
a "makes you smile"
a "makes you laugh"
a "makes your day"
a "makes you laugh"
a "made in linux"
a "Asubject name hereA"
a "that's what she said!"
a "remember when the platform was sliding into the fire pit?"
a "that was great"
a "l'll go with true"
a "when in rome. do the romans"
a "early to bed. early to catch the worm!"
a "here is the map! where do you wish to go?"
a "that's what she said!"
a "doctor dumb can go screw himself!"
a "that's what she said!"
a "did you know that the witch-woman jenka once had a brother?"
a "from somewhere, a transmission"
a "huzzah!"
a "it's like earthgubbs who plumses into milk!"
a "made with lOve"
a "when in rome, do the romans"
a "this incident will be reported"
a "it's dangerous to go alone, take this"
a "i am error"
a "that's what she said!"
a "l really want to know if you like japanese squids!"
a "do a barrel roll!"
a "spur is better than nemesis"
a "<3"
a "made with lOve"
a ":ppppppppppppppppppppp"
a "when in rome, do the romans"
a "that's what she said!"
a ":ppppppppppppppppppppp"
a "that's what she said!"
a ":ppppppppppppppppppppp"
a ":3"
a "or is it?"
a "i like you"
a "i wonder who you are"
a "i should make nachos"
a "sudo make me a sandwich"
a "science works"
a "made with lOve"
a "who are you? how did you get into my house?"
a "notifying field agents"
a "boom de yada!"
a "must compile kernel"
a "who you gonna call?"
a "sizzle sizzle"
a "history is written by those who own functional pens"
a "the egg came first"
a "it's super effective!"
a "like a boss!"
a "would you like to complete a survey?"
a "are you still there?"
a "there you are"
a "justin bailey"
a "narpassword"
a "wild loopbox appeared!"
a "god jul!"
a "snel hest"
a "marvelous!"
a "made with lOve"
a "l wonder what's for dinner."
a "once upon a time..."
a "your mom"
a "it's on like dAnkey kAng!"
a "l've got balls of steel!"
a "nyan nyan nyan nyan"
a "l wish i were a bird!"
a "l buy sausage!"
a "hey l just met your and this is crazy"
a "so play me maybe?"
a "squadallah! we're off!"
a "music by the gunkmeister"
a "fire in disguise!"
a "it's awesome!"
a "all toasters toast toast!"
a "all toasters toast bread!"
a "bread factory!"
a "...or is it that it lets you forget yourself?"
a "royal rainbow!"
a "tssssssss... boom!"
a "some stay dry and others feel the pain"
a "we should totally open a bar!"
a "l think it's pronounced ''lah-mey''."
a "l would walk 9000 miles!"
a "don't you know about the bird?"
a "everybody's talking about the bird!"
a "bah-bah-bah bird bird bird"
a "very super famous!"
a "not in 3d!"
a "when l'm alone l count myself!"
a "not really invisible"
a "for great justice!"
a "ffffffffuuuuuuuuuuuuuuu"
a "you've met with a terrible fate, haven't you?"
a "made in sweden"
a "written in lua"
a "made in sweden"
a "l miss all my apps"
a "trololololo"
a "true story"
a "early to bed, early to catch the worm"
a "l mean, seriously now?"
a "won't trick you with reverse psycology"
a "remember when the platform was sliding into the fire pit?"
a "two plus two equals ten in base four"
a "the second best idea we've ever had!"
a "beat all the levels!!"
a "one does not simply beat this game"
a "one does not simply find easter eggs"
a "l'm your father"
a "like a sir"
a "sata andagi"
a "which seat can i take?"
a "fun fun fun fun"
a "not for the ps triple!"
a "five out of five toasts!"
a "there's a hole in your dungaree"
a "pain."
a "there are so many different kinds of trees"
a "come back whenever you are ready"
a "lamp oil? rope? bombs?"
a "it's yours my friend"
a "trust me, l'm an engineer"
a "most doctors agree that breathing is an excellent way to stay alive"
a "insert joke here"
a "passion for exploring"
a "why are you reading this?"


return tits
